import { db } from '../src/lib/db'

async function main() {
  // Create admin user
  await db.admin.upsert({
    where: { username: 'admin' },
    update: {},
    create: {
      username: 'admin',
      password: 'mokamotors2024',
    },
  })

  // Create motorbikes
  const motorbikes = [
    {
      name: 'Honda CBR600RR',
      brand: 'Honda',
      category: 'Sport',
      price: 12500000,
      year: 2023,
      engineSize: '599cc',
      mileage: '2,500 km',
      color: 'Red',
      description: 'The legendary CBR600RR delivers exhilarating performance with its inline-four engine, razor-sharp handling, and track-ready precision. Perfect for riders who demand the best in sport biking.',
      imageUrl: '/images/bike-honda-cbr.png',
      featured: true,
      isNewStock: true,
    },
    {
      name: 'Kawasaki Ninja 400',
      brand: 'Kawasaki',
      category: 'Sport',
      price: 8900000,
      year: 2024,
      engineSize: '399cc',
      mileage: '800 km',
      color: 'Green',
      description: 'The Ninja 400 delivers the thrill of a superbike in a lightweight, accessible package. Its parallel-twin engine offers smooth power delivery and exceptional fuel efficiency.',
      imageUrl: '/images/bike-kawasaki-ninja.png',
      featured: true,
      isNewStock: true,
    },
    {
      name: 'KTM Duke 390',
      brand: 'KTM',
      category: 'Standard',
      price: 9500000,
      year: 2023,
      engineSize: '373cc',
      mileage: '3,200 km',
      color: 'Orange',
      description: 'The KTM Duke 390 is the ultimate naked bike for urban warriors. Aggressive styling, punchy performance, and cutting-edge technology make every ride an adventure.',
      imageUrl: '/images/bike-ktm-duke.png',
      featured: true,
      isNewStock: false,
    },
    {
      name: 'Yamaha YZF-R1',
      brand: 'Yamaha',
      category: 'Sport',
      price: 22000000,
      year: 2023,
      engineSize: '998cc',
      mileage: '1,800 km',
      color: 'Blue',
      description: 'The YZF-R1 represents the pinnacle of Yamaha\'s sport bike technology. With its crossplane crank engine and advanced electronics, it delivers superbike performance for the street.',
      imageUrl: '/images/bike-yamaha-r1.png',
      featured: true,
      isNewStock: false,
    },
    {
      name: 'Honda CRF250L',
      brand: 'Honda',
      category: 'Off-Road',
      price: 7800000,
      year: 2023,
      engineSize: '249cc',
      mileage: '4,100 km',
      color: 'Red/White',
      description: 'The CRF250L is built for adventure. Whether you\'re commuting through the city or exploring off-road trails, this dual-sport motorcycle handles it all with Honda reliability.',
      imageUrl: '/images/bike-honda-crf.png',
      featured: false,
      isNewStock: false,
    },
    {
      name: 'Kawasaki Vulcan S',
      brand: 'Kawasaki',
      category: 'Cruiser',
      price: 11200000,
      year: 2022,
      engineSize: '649cc',
      mileage: '5,600 km',
      color: 'Black',
      description: 'The Vulcan S combines Kawasaki\'s legendary performance with cruiser comfort. Its adjustable Ergo-Fit system ensures a perfect ride for every body type.',
      imageUrl: '/images/bike-kawasaki-vulcan.png',
      featured: false,
      isNewStock: true,
    },
    {
      name: 'Yamaha MT-07',
      brand: 'Yamaha',
      category: 'Standard',
      price: 10200000,
      year: 2024,
      engineSize: '689cc',
      mileage: '500 km',
      color: 'Grey',
      description: 'The MT-07 is Yamaha\'s best-selling naked bike, loved for its torquey parallel-twin engine, lightweight chassis, and playful handling. The perfect do-it-all motorcycle.',
      imageUrl: '/images/bike-yamaha-mt07.png',
      featured: false,
      isNewStock: true,
    },
    {
      name: 'KTM RC 390',
      brand: 'KTM',
      category: 'Sport',
      price: 8200000,
      year: 2023,
      engineSize: '373cc',
      mileage: '2,100 km',
      color: 'Orange/White',
      description: 'The RC 390 brings track-day excitement to the street. With its razor-sharp handling, powerful single-cylinder engine, and aggressive styling, it\'s born to race.',
      imageUrl: '/images/bike-ktm-rc390.png',
      featured: false,
      isNewStock: false,
    },
    {
      name: 'Honda PCX160',
      brand: 'Honda',
      category: 'Scooter',
      price: 4500000,
      year: 2024,
      engineSize: '156cc',
      mileage: '200 km',
      color: 'White',
      description: 'The PCX160 is the premium scooter for modern urban commuting. With its refined engine, spacious storage, and elegant design, every ride is first class.',
      imageUrl: '/images/bike-honda-pcx.png',
      featured: false,
      isNewStock: false,
    },
    {
      name: 'Yamaha MT-09 SP',
      brand: 'Yamaha',
      category: 'Standard',
      price: 18500000,
      year: 2024,
      engineSize: '890cc',
      mileage: '350 km',
      color: 'Blue/Black',
      description: 'The MT-09 SP takes the already incredible MT-09 to new heights with premium KYB suspension, R1-style brakes, and special color scheme. The ultimate hyper naked.',
      imageUrl: '/images/bike-yamaha-r1.png',
      featured: true,
      isNewStock: true,
    },
  ]

  for (const bike of motorbikes) {
    await db.motorbike.create({ data: bike })
  }

  // Create spare parts
  const spareParts = [
    {
      name: 'Brake Pad Set (Front)',
      type: 'Brakes',
      brand: 'Honda',
      compatibility: 'Honda CBR, CB, CRF series',
      price: 120000,
      description: 'High-quality front brake pad set for Honda motorcycles. Provides excellent stopping power and long-lasting performance. OEM equivalent quality.',
      imageUrl: '/images/part-brakes.png',
      inStock: true,
      featured: true,
    },
    {
      name: 'Chain & Sprocket Kit',
      type: 'Chain/Sprocket',
      brand: 'Universal',
      compatibility: 'Most 250cc-600cc motorcycles',
      price: 250000,
      description: 'Premium gold chain with steel sprockets. 520 pitch, suitable for most mid-size motorcycles. Includes front and rear sprockets with connecting link.',
      imageUrl: '/images/part-chain.png',
      inStock: true,
      featured: true,
    },
    {
      name: 'Air Filter Element',
      type: 'Filters',
      brand: 'Yamaha',
      compatibility: 'Yamaha YZF, MT, FZ series',
      price: 45000,
      description: 'Genuine quality air filter element for Yamaha motorcycles. Ensures optimal airflow and engine protection. Easy installation, direct replacement.',
      imageUrl: '/images/part-filters.png',
      inStock: true,
      featured: false,
    },
    {
      name: 'Sport Tire (Rear) 180/55ZR17',
      type: 'Tires',
      brand: 'Universal',
      compatibility: 'Most sport bikes 600cc-1000cc',
      price: 380000,
      description: 'High-performance sport tire for rear wheel. Excellent grip in wet and dry conditions. ZR speed rating for high-speed stability. Long-lasting compound.',
      imageUrl: '/images/part-tire.png',
      inStock: true,
      featured: true,
    },
    {
      name: 'LED Headlight Assembly',
      type: 'Electrical',
      brand: 'Kawasaki',
      compatibility: 'Kawasaki Ninja 300/400/650',
      price: 450000,
      description: 'Modern LED headlight assembly with DRL. Bright white light for superior visibility. Plug-and-play installation. Energy efficient and long-lasting.',
      imageUrl: '/images/part-electrical.png',
      inStock: true,
      featured: false,
    },
    {
      name: 'Engine Gasket Set',
      type: 'Engine Parts',
      brand: 'Honda',
      compatibility: 'Honda CBR600RR 2013-2023',
      price: 180000,
      description: 'Complete engine gasket set including head gasket, base gasket, and all seals. High-temperature resistant material. Essential for engine rebuilds.',
      imageUrl: '/images/part-engine.png',
      inStock: true,
      featured: false,
    },
    {
      name: 'Fairing Panel Set (Left Side)',
      type: 'Body Parts',
      brand: 'KTM',
      compatibility: 'KTM Duke 390 2017-2023',
      price: 320000,
      description: 'Left side fairing panel set for KTM Duke 390. Factory-matched orange color with graphics. UV-resistant paint for long-lasting appearance.',
      imageUrl: '/images/part-body.png',
      inStock: false,
      featured: false,
    },
    {
      name: 'Exhaust Slip-On Muffler',
      type: 'Accessories',
      brand: 'Universal',
      compatibility: 'Most 250cc-600cc motorcycles',
      price: 550000,
      description: 'Stainless steel slip-on muffler with carbon fiber end cap. Improved sound and slight performance gain. Easy bolt-on installation. Includes mounting hardware.',
      imageUrl: '/images/part-accessories.png',
      inStock: true,
      featured: true,
    },
    {
      name: 'Oil Filter',
      type: 'Filters',
      brand: 'Universal',
      compatibility: 'Most Japanese motorcycles',
      price: 15000,
      description: 'Premium oil filter for Japanese motorcycles. High filtration efficiency to protect your engine. Easy spin-on installation. Change with every oil service.',
      imageUrl: '/images/part-filters.png',
      inStock: true,
      featured: false,
    },
    {
      name: 'Brake Disc Rotor (Front)',
      type: 'Brakes',
      brand: 'Yamaha',
      compatibility: 'Yamaha YZF-R1, MT-09 series',
      price: 280000,
      description: 'Stainless steel front brake disc rotor. Precision-drilled for heat dissipation. Provides consistent braking performance. Direct OEM replacement.',
      imageUrl: '/images/part-brakes.png',
      inStock: true,
      featured: false,
    },
  ]

  for (const part of spareParts) {
    await db.sparePart.create({ data: part })
  }

  console.log('Seed data created successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
